### ISSUE TITLE
OTP verification

### ISSUE THREAD

**Issue by diliprao0506** [azizur-rehman/SSTalk#8]
Hi i'm facing the problem at otp verification.
Getting the error message "Failed to send OTP. Perhaps you are using an emulator "

**Comment by azizur-rehman** [comment]
Are you talking about the live app available at the PlayStore or from the source code itself?

**Comment by diliprao0506** [comment]
From the source code, I've build from android studio

**Comment by azizur-rehman** [comment]
Yeah I figured but was waiting on your confirmation. This is because your **SHA1** is different than mine. I am guessing you have created your own firebase project, haven't you? You won't be able to run the project unless you have setup your own firebase project. Because that's how I will be able to protect my current database and I've already mentioned in the Readme file. Hope it helps.
